#import "cits.typ": mk_footnote, statutory_text, block_quote

= Introduction

As of August 2022, Pew Research found that 16% of American adults report having invested in, traded, or used a cryptocurrency; uptake is particularly high among men ages 18 to 29, with 42% reporting that they invested in, traded, or used a cryptocurrency, and 49% of American adults report having heard at least a little about non-fungible tokens (NFTs).#mk_footnote("pew_atp")

Financial institutions operating in the United States have aggressively marketed virtual assets and related products and services through channels commonly used to attract retail investment, with everyone from sports stars,#mk_footnote("tom_brady_ftx") sitting US Senators,#mk_footnote("lummis_gillibrand") and all manner of miscellaneous celebrity#mk_footnote("sec_kardashian") lining up to preach the virtues of this new asset class. While the nature of digital assets has always left the door open uncomfortably wide for theft, fraud, and loss by acccident, recent years have been particularly unkind to crypto investors, increasingly due to institutional fraud.

The primary source of guidance from the IRS concerning the tax treatment of virtual currency is Notice 2014-21,#mk_footnote("notice") published in March of 2014, which treats virtual currency as property, applying general tax principles concerning property. While the classification of virtual currency as property can be justified by viewing the issue through a historical lens, it also creates a number of gray areas in addition to unintuitive and seemingly unfair tax results. Furthermore, the uncertainty which once obscured the purpose and practical implications of initial coin offerings has all but vanished in the years since publication of 2014-12; what may have initially appeared to be a sagelike “wait and see” approach by the IRS may quickly begin to look like a case of government agency arthritis if nothing is done, particularly as elements of the TCJA are set to expire in 2026.#mk_footnote("2026_examples")

Empirically, the once rising star that was virtual currency is now falling; basic economics would suggest that the precipitous drop in asset prices reflects (at least in part) a decrease in interest and demand. Technical experts have failed to make significant progress on some of the more fundamental problems plaguing adoption, like key management, transaction volume, and security. The double-edged sword of price volatility remains a source of chaos in virtual currency markets, while newcomers and veterans alike are growing increasingly tired of discovering that a fraud lies under seemingly every stone in the crypto garden.

That being said, tax authorities should prepare themselves to deal with these new assets on a permanent basis. The enduring legacy of Bitcoin will be that it popularized a practical solution to the problem of transferring economic value over the internet without a trusted intermediary capable of employing enforcement authority derived from a sovereign. Even if the largest currently operating networks were to disappear, something else would almost certainly take their place under a different name, perhaps employing a new wrinkle on the idea of consensus, resilience to attack, or privacy. There are demographics, including prviacy maximalists, digital goldbugs, hackers, and participants in all manner of black market, for whom the value of these assets will never be zero. Proper preparation necessarily includes adaptation in the realm of tax law, empowering authorities to deal with these new asset classes fairly and efficiently.
